name: image_restoration
channels:
  - defaults
dependencies:
  - python=3.9
  - tensorflow=2.8.0
  - opencv=4.5.5
  - scikit-image=0.18.3
  - matplotlib=3.4.3
  - numpy=1.21.4
  - scipy=1.7.3
  - pip
  - pip:
    - opencv-python==4.5.5.62  # This is required if opencv from conda-forge doesn't work as expected

